version: '3.8'
services:
  tensorflow:
    image: nvcr.io/nvidia/tensorflow:23.06-tf2-py3
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./notebooks:/workspace
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]
